name: Containerized Node App Deployment

on:
 push:
   branches: [ main ]   
env:
  IMAGE_VERSION: ${{github.run_number}}
    
jobs:
  build:
    runs-on: devopsmolvi

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build . --tag devopsmolvi/webimages:$IMAGE_VERSION
  
    - name: Logging into the Docker Hub
      uses: docker/login-action@v1
      with:
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASS }}
          
    - name: Pushing the Image to Docker Hub
      run: |
           docker push devopsmolvi/webimages:$IMAGE_VERSION

    - name: SSH Authentication with the Deployment Server
      run: |
           ssh -itt -oStrictHostKeyChecking=no 35.224.255.103 
           echo "${{ secrets.DOCKER_PASS }}" | docker login --username "${{ secrets.DOCKER_USER }}" --password-stdin 
           docker pull devopsmolvi/webimages:$IMAGE_VERSION
           docker run -it -d -p 8080:8080 --restart unless-stopped --name webserver devopsmolvi/webimages:$IMAGE_VERSION
